/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class GuitarMidiAudioProcessorEditor  : public AudioProcessorEditor, public ComboBox::Listener
{

public:


    GuitarMidiAudioProcessorEditor (GuitarMidiAudioProcessor&);
    ~GuitarMidiAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

    void comboBoxChanged(ComboBox* box) override;

private:

    //menu for midi devices
    ComboBox m_midiOutputBox;

    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    GuitarMidiAudioProcessor& m_processor;


    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (GuitarMidiAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
